### ISSUE TITLE
Sending supervisor state data

### ISSUE THREAD

**Issue by yassine-kr** [molr/molr-remote#12] opened 2018-05-04 15:40 UTC
When an instantiation request is sent to MolR server, it has to be delegated to an appropriate supervisor.
The acceptance of a mission execution is determined by the combination of the supervisor static state and the supervisor dynamic state.
- Static state: type of missions that can be run on the supervisor host, max number of JVM, etc
- Dynamic state: current number of running missions, etc

To choose an adequate supervisor, MolR server must have informations about the state of each registered supervisor. 

When should the state data be requested and sent to MolR server?
- It can be sent to MolR server after each time interval.
- Or it can be requested only if necessary (ex. when MolR server needs to choose an appropriate supervisor).

**Comment by makemeunsee** [comment] 2018-05-09 08:02
duplicate of #3
see: https://github.com/molr/molr-remote/issues/3#issuecomment-387652176

**Closed** 2018-07-27 15:00 UTC
